# Generated by Django 4.2.11 on 2025-02-20 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.board'),
        ),
        migrations.AddField(
            model_name='student',
            name='normalized_marks',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
