# Generated by Django 4.2.11 on 2025-02-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_student_board_student_normalized_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QualifiedMark',
        ),
    ]
