# Generated by Django 3.2.12 on 2025-02-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_remove_student_aadhaar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.documentname'),
        ),
    ]
