# Generated by Django 3.2.12 on 2025-02-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_rename_document_name_documentname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='DocumentName',
        ),
    ]
