# Generated by Django 4.2.11 on 2025-03-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_remove_teacher_department_alter_teacher_user'),
        ('admission', '0011_auto_20250228_0655'),
    ]

    operations = [
    ]
