# Generated by Django 5.1.7 on 2025-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0017_student_tc_no_student_year_of_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tc_status',
            field=models.BooleanField(default=False),
        ),
    ]
