# Generated by Django 5.1.7 on 2025-03-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0021_student_photo'),
    ]

    operations = [
    ]
