# Generated by Django 5.1.7 on 2025-03-13 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0022_auto_20250313_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfercertificate',
            old_name='date_of_issue',
            new_name='date_of_admission',
        ),
        migrations.RenameField(
            model_name='transfercertificate',
            old_name='stud',
            new_name='student',
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='admission_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='last_exam_details',
            field=models.TextField(default='Kannur University'),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='programme',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='scholarship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='date_of_application',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='tc_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
