# Generated by Django 5.1.7 on 2025-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0023_rename_date_of_issue_transfercertificate_date_of_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='date_of_admission',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='dob',
            field=models.DateField(),
        ),
    ]
