# Generated by Django 5.1.7 on 2025-03-13 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_alter_transfercertificate_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='date_of_issuing_tc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
