# Generated by Django 5.1.7 on 2025-03-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_transfercertificate_date_of_issuing_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason_description',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.reason'),
        ),
    ]
