# Generated by Django 5.1.7 on 2025-03-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_alter_reason_reason_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
