# Generated by Django 5.1.7 on 2025-03-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.reason'),
        ),
    ]
