# Generated by Django 5.1.7 on 2025-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0035_alter_transfercertificate_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='scholarship',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
