# Generated by Django 5.1.7 on 2025-04-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0036_alter_transfercertificate_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_admission',
            field=models.IntegerField(default=2025),
        ),
    ]
