# Generated by Django 5.1.7 on 2025-04-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0039_transfercertificate_details_of_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('parent_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('date_of_admission', models.DateField()),
                ('academic_year', models.CharField(editable=False, max_length=20)),
                ('date_of_issue', models.DateField()),
                ('reg_no', models.CharField(blank=True, max_length=100, null=True)),
                ('month_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.transfercertificate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to='admission.student')),
            ],
        ),
    ]
