# Generated by Django 5.1.7 on 2025-04-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0042_rename_date_of_admission_coursecertificate_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
