# Generated by Django 4.2.11 on 2025-02-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='normalized_marks',
            new_name='normalized_mark',
        ),
    ]
