# Generated by Django 3.2.12 on 2025-02-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20250228_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentname',
            old_name='document_name',
            new_name='name',
        ),
    ]
