# Generated by Django 3.2.12 on 2025-02-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_auto_20250228_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctype'),
        ),
    ]
