# Generated by Django 4.2.11 on 2025-03-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0012_merge_20250306_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctype'),
        ),
    ]
