# Generated by Django 5.1.7 on 2025-03-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_alter_customuser_groups_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
