# Generated by Django 5.1.7 on 2025-03-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0018_student_tc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tc_status',
        ),
    ]
