# Generated by Django 5.1.7 on 2025-03-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0019_remove_student_tc_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tc_no',
        ),
    ]
