# Generated by Django 5.1.7 on 2025-03-13 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0025_rename_last_exam_details_transfercertificate_details_of_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='date_of_leaving',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='dues_cleared',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='mode_of_study',
            field=models.CharField(default='Regular', max_length=20),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='month_year',
            field=models.CharField(default='03-2025', max_length=7),
        ),
        migrations.AddField(
            model_name='transfercertificate',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
