# Generated by Django 5.1.7 on 2025-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_transfercertificate_date_of_leaving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfercertificate',
            name='month_year',
            field=models.DateField(),
        ),
    ]
