# Generated by Django 5.1.7 on 2025-03-13 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_alter_reason_reason_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='reason_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transfercertificate',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admission.reason'),
        ),
    ]
