# Generated by Django 5.1.7 on 2025-04-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0037_alter_student_year_of_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfercertificate',
            name='details_of_exam',
        ),
    ]
