# Generated by Django 5.1.7 on 2025-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0038_remove_transfercertificate_details_of_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='details_of_exam',
            field=models.TextField(default='Kannur University'),
        ),
    ]
