# Generated by Django 5.1.7 on 2025-04-24 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0040_coursecertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecertificate',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.department'),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='month_year',
            field=models.CharField(max_length=10),
        ),
    ]
