# Generated by Django 5.1.7 on 2025-04-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0041_alter_coursecertificate_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecertificate',
            old_name='date_of_admission',
            new_name='dob',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='department',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='month_year',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='coursecertificate',
            name='reg_no',
        ),
    ]
