# Generated by Django 5.1.7 on 2025-05-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0043_delete_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
